### ISSUE TITLE
Device testing

### ISSUE THREAD

**Issue by RobertPeek** [deltanet/adapt_delta_default#2]
General:

- Submit button on mobile looks odd as height is different to the Show feedback.
- Question icon could be added to the questions as a class.

LMS:

- Add images.

Media:

- Add deltanet poster image to intro video.
- Tabbing breaks when focus gets to the CC button on the player.

Slider:

- Slider handle colour needs to match button colour.
- Highlighted scale item colour needs to be changed to something other than the button colour, perhaps the rollover colour would be OK.
- Numbers in scale need to be button colour and rollover needs to match button rollover as currently can’t see number on rollover.
- If you drag slider and release outside of the handle, it doesn’t register the mouse out/release.
- Slider doesn’t respond to RTL setting.

Character Text:

- Bg colour on speech box needs to pull in the primary colour.

Tabs:

- Transition between item is very clunky and flashes badly.

Hotgraphic:

- Rollover colour needed on close button.
- Tab order breaks when popup open, jumps to instruction text on previous narrative component.

Accordion:

- Add images to show that it can be done.
- As an enhancement make text and images side by side, but just stacked on mobile.
- Item text is aligned wrong in RTL. *** check buttons.less > &.base class. 

PLP:

- Progress bar is not aligned properly on the locked/dead state.

Narrative:

- RTL support breaks on the forward and back arrows.

**Comment by mayuir2014** [comment]
Here is an update of the issues:

#### General:

* Submit button on mobile looks odd as height is different to the Show feedback. - ***Amended.***
* Question icon could be added to the questions as a class. - ***Amended.***

#### LMS:

- Add images. - ***Added placeholder for now.***

#### Media:

- Add deltanet poster image to intro video. - ***Amended.***
- Tabbing breaks when focus gets to the CC button on the player. - ***Amended.***

#### Slider:

- Slider handle colour needs to match button colour. - ***Amended.***
- Highlighted scale item colour needs to be changed to something other than the button colour, perhaps the rollover colour would be OK. - ***Amended.***
- Numbers in scale need to be button colour and rollover needs to match button rollover as currently can’t see number on rollover. - ***Amended.***
- If you drag slider and release outside of the handle, it doesn’t register the mouse out/release. - ***Issue resolved in adapt-contrib-slider - v2.0.2***
- Slider doesn’t respond to RTL setting. - ***To be actioned***

#### Character Text:

- Bg colour on speech box needs to pull in the primary colour. - ***Amended.***

#### Tabs:

- Transition between item is very clunky and flashes badly. - ***Removed flashing + slide-up - Added fade-in***

#### Hotgraphic:

- Rollover colour needed on close button. - ***The current default supplied was set to @white. Have left this as is, as alot of components utilise this @variable. Have amended in theme/hotgraphic.less***
- Tab order breaks when popup open, jumps to instruction text on previous narrative component. - ***To be actioned***

#### Accordion:

- Add images to show that it can be done. - ***Amended.***
- As an enhancement make text and images side by side, but just stacked on mobile. - ***To be actioned***
- Item text is aligned wrong in RTL. *** check buttons.less > &.base class. - ***Amended in accordion.less***

#### PLP:

- Progress bar is not aligned properly on the locked/dead state. - *** This only occurs when links are locked - To be actioned***

As an additional issue, I found that the Audio element of the drawer also offsets the text within incorrectly. - ***To be actioned***

#### Narrative:

- RTL support breaks on the forward and back arrows. - ***To be actioned***

**Comment by mayuir2014** [comment]
Additional issues:

#### PLP
- Found that the Audio element of the drawer also offsets the text within incorrectly.

#### Tabbing
- In accessibility mode, when tabbing through the narrative and hotgraphic components on topic 1, it doesn't tab correctly.
